{
  "schema_version": "1.4.0",
  "id": "GHSA-xpf8-484v-j9w6",
  "modified": "2025-07-31T21:31:54Z",
  "published": "2025-07-31T21:31:54Z",
  "aliases": [
    "CVE-2025-45768"
  ],
  "details": "pyjwt v2.10.1 was discovered to contain weak encryption.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2025-45768"
    },
    {
      "type": "WEB",
      "url": "https://gist.github.com/ZupeiNie/6f65e564f2067b876321d3dfdbb76569"
    },
    {
      "type": "WEB",
      "url": "https://github.com/jpadilla"
    },
    {
      "type": "WEB",
      "url": "https://github.com/jpadilla/pyjwt"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-311"
    ],
    "severity": "HIGH",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2025-07-31T21:15:27Z"
  }
}