{
  "schema_version": "1.4.0",
  "id": "GHSA-7gc4-cwgf-384p",
  "modified": "2022-11-22T03:30:59Z",
  "published": "2022-11-18T00:30:19Z",
  "aliases": [
    "CVE-2022-38165"
  ],
  "details": "WithSecure through 2022-08-10 allows attackers to cause a denial of service (issue 4 of 5).",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-38165"
    },
    {
      "type": "WEB",
      "url": "https://www.withsecure.com/en/support/security-advisories/cve-2022-38165"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-22"
    ],
    "severity": "CRITICAL",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2022-11-17T23:15:00Z"
  }
}