{
  "schema_version": "1.4.0",
  "id": "GHSA-9mpr-24m6-767p",
  "modified": "2025-05-06T15:30:35Z",
  "published": "2022-05-13T01:31:06Z",
  "aliases": [
    "CVE-2018-18066"
  ],
  "details": "snmp_oid_compare in snmplib/snmp_api.c in Net-SNMP before 5.8 has a NULL Pointer Exception bug that can be used by an unauthenticated attacker to remotely cause the instance to crash via a crafted UDP packet, resulting in Denial of Service.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2018-18066"
    },
    {
      "type": "WEB",
      "url": "https://dumpco.re/blog/net-snmp-5.7.3-remote-dos"
    },
    {
      "type": "WEB",
      "url": "https://security.netapp.com/advisory/ntap-20181107-0001"
    },
    {
      "type": "WEB",
      "url": "https://sourceforge.net/p/net-snmp/code/ci/7ffb8e25a0db851953155de91f0170e9bf8c457d"
    },
    {
      "type": "WEB",
      "url": "https://sourceforge.net/p/net-snmp/code/ci/f23bcd3ac6ddee5d0a48f9703007ccc738914791"
    },
    {
      "type": "WEB",
      "url": "https://www.oracle.com/technetwork/security-advisory/cpuoct2019-5072832.html"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-476"
    ],
    "severity": "HIGH",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2018-10-08T18:29:00Z"
  }
}