{
  "schema_version": "1.4.0",
  "id": "GHSA-c8mq-83h4-gm57",
  "modified": "2022-12-22T15:30:21Z",
  "published": "2022-12-18T06:31:09Z",
  "aliases": [
    "CVE-2022-47517"
  ],
  "details": "An issue was discovered in the libsofia-sip fork in drachtio-server before 0.8.19. It allows remote attackers to cause a denial of service (daemon crash) via a crafted UDP message that causes a url_canonize2 heap-based buffer over-read because of an off-by-one error.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-47517"
    },
    {
      "type": "WEB",
      "url": "https://github.com/drachtio/drachtio-server/issues/243"
    },
    {
      "type": "WEB",
      "url": "https://github.com/davehorton/sofia-sip/commit/22c1bd191f0acbf11f0c0fbea1845d9bf9dcd47e"
    },
    {
      "type": "WEB",
      "url": "https://github.com/davehorton/sofia-sip/commit/bfc79d85c8f3a4798a3305fb98f5a11c11d0d29f"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-193",
      "CWE-787"
    ],
    "severity": "HIGH",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2022-12-18T05:15:00Z"
  }
}