{
  "schema_version": "1.4.0",
  "id": "GHSA-cch3-2vm3-v73j",
  "modified": "2025-04-20T03:50:41Z",
  "published": "2025-04-20T03:50:41Z",
  "aliases": [
    "CVE-2025-43929"
  ],
  "details": "open_actions.py in kitty before 0.41.0 does not ask for user confirmation before running a local executable file that may have been linked from an untrusted document (e.g., a document opened in KDE ghostwriter).",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:L/AC:H/PR:N/UI:R/S:C/C:L/I:L/A:N"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2025-43929"
    },
    {
      "type": "WEB",
      "url": "https://github.com/kovidgoyal/kitty/commit/ce5cfdd9caf44c538af800a07162e1f49bd53c35"
    },
    {
      "type": "WEB",
      "url": "https://ghostwriter.kde.org/documentation/#links"
    },
    {
      "type": "WEB",
      "url": "https://github.com/kovidgoyal/kitty/compare/v0.40.1...v0.41.0"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-346"
    ],
    "severity": "MODERATE",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2025-04-20T03:15:36Z"
  }
}