{
  "schema_version": "1.4.0",
  "id": "GHSA-w55r-6729-mr2m",
  "modified": "2025-06-18T12:30:50Z",
  "published": "2025-06-18T12:30:50Z",
  "aliases": [
    "CVE-2022-50143"
  ],
  "details": "In the Linux kernel, the following vulnerability has been resolved:\n\nintel_th: Fix a resource leak in an error handling path\n\nIf an error occurs after calling 'pci_alloc_irq_vectors()',\n'pci_free_irq_vectors()' must be called as already done in the remove\nfunction.",
  "severity": [],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-50143"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/086c28ab7c5699256aced0049aae9c42f1410313"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/859342220accd0d332864fafbf4e3d2d0492bc3f"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/9b5469573a274729bdb04b60a8d71f8d09940a31"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/a8f3b78b1f8e959d06801ae82149f140a75724e8"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/ed4d5ecb7d7fd80336afb2f9ac6685651a6aa32f"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/fae9da7d4c2ccad3792de03e3cac1fe2bfabb73d"
    }
  ],
  "database_specific": {
    "cwe_ids": [],
    "severity": null,
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2025-06-18T11:15:44Z"
  }
}