{
  "schema_version": "1.4.0",
  "id": "GHSA-r68f-4xcm-3xr6",
  "modified": "2025-04-20T03:48:42Z",
  "published": "2022-05-13T01:40:58Z",
  "aliases": [
    "CVE-2017-1000158"
  ],
  "details": "CPython (aka Python) up to 2.7.13 is vulnerable to an integer overflow in the PyString_DecodeEscape function in stringobject.c, resulting in heap-based buffer overflow (and possible arbitrary code execution)",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2017-1000158"
    },
    {
      "type": "WEB",
      "url": "https://bugs.python.org/issue30657"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2017/11/msg00035.html"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2017/11/msg00036.html"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2018/09/msg00030.html"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2018/09/msg00031.html"
    },
    {
      "type": "WEB",
      "url": "https://security.gentoo.org/glsa/201805-02"
    },
    {
      "type": "WEB",
      "url": "https://security.netapp.com/advisory/ntap-20230216-0001"
    },
    {
      "type": "WEB",
      "url": "https://www.debian.org/security/2018/dsa-4307"
    },
    {
      "type": "WEB",
      "url": "http://www.securitytracker.com/id/1039890"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-190"
    ],
    "severity": "CRITICAL",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2017-11-17T05:29:00Z"
  }
}