{
  "schema_version": "1.4.0",
  "id": "GHSA-f372-2jpp-jxj9",
  "modified": "2025-05-01T15:31:48Z",
  "published": "2025-05-01T15:31:48Z",
  "aliases": [
    "CVE-2022-49811"
  ],
  "details": "In the Linux kernel, the following vulnerability has been resolved:\n\ndrbd: use after free in drbd_create_device()\n\nThe drbd_destroy_connection() frees the \"connection\" so use the _safe()\niterator to prevent a use after free.",
  "severity": [],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-49811"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/7d93417d596402ddd46bd76c721f205d09d0d025"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/813a8dd9c45fd46f5cbbfbedf0791afa7740ccf5"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/9ed51414aef6e59e832e2960f10766dce2d5b1a1"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/a7a1598189228b5007369a9622ccdf587be0730f"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/bf47ca1b35fc1f55091ffaff5fbe41ea0c6f59a1"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/c2a00b149836d60c222930bbea6b2139caf34d4f"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/fc1897f16ebcfd22364f2afcc27f53a740f3bc7a"
    }
  ],
  "database_specific": {
    "cwe_ids": [],
    "severity": null,
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2025-05-01T15:16:04Z"
  }
}