{
  "schema_version": "1.4.0",
  "id": "GHSA-7xm3-5xp5-q98v",
  "modified": "2025-04-20T03:31:55Z",
  "published": "2022-05-14T01:54:40Z",
  "aliases": [
    "CVE-2017-5601"
  ],
  "details": "An error in the lha_read_file_header_1() function (archive_read_support_format_lha.c) in libarchive 3.2.2 allows remote attackers to trigger an out-of-bounds read memory access and subsequently cause a crash via a specially crafted archive.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2017-5601"
    },
    {
      "type": "WEB",
      "url": "https://github.com/libarchive/libarchive/commit/98dcbbf0bf4854bf987557e55e55fff7abbf3ea9"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2018/11/msg00037.html"
    },
    {
      "type": "WEB",
      "url": "https://secunia.com/secunia_research/2017-3"
    },
    {
      "type": "WEB",
      "url": "http://www.securityfocus.com/bid/95837"
    },
    {
      "type": "WEB",
      "url": "http://www.securitytracker.com/id/1037974"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-125"
    ],
    "severity": "HIGH",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2017-01-27T22:59:00Z"
  }
}